// Single source of truth — every admin route MUST be mapped here
// CI guard: any route NOT in this map rejects all non-super-admins

export const ROUTE_PERMISSIONS: Record<string, string> = {
  // Dashboard
  'GET /me': 'dashboard:read',
  'GET /stats/overview': 'statistics:read',
  'GET /stats/health': 'statistics:read',
  'GET /stats/content': 'statistics:read',
  'GET /stats/community': 'statistics:read',
  'GET /stats/moderation': 'statistics:read',
  'GET /stats/categories': 'statistics:read',
  'GET /stats/trends': 'statistics:read',
  'GET /stats/quality': 'statistics:read',
  'GET /stats/traffic': 'statistics:read',
  'GET /stats/traffic/lurkers': 'statistics:read',
  'GET /stats/traffic/conversion': 'statistics:read',
  'GET /stats/users/reengagement': 'statistics:read',
  'GET /stats/submissions': 'statistics:read',
  'GET /stats/users/lifecycle': 'statistics:read',
  'GET /stats/alerts': 'statistics:read',
  'GET /stats/compare': 'statistics:read',
  'GET /stats/notifications': 'statistics:read',
  'GET /stats/search/overview': 'search:read',
  'GET /stats/search/queries': 'search:read',
  'GET /stats/search/relevance': 'search:read',
  'GET /stats/search/trends': 'search:read',
  'GET /stats/search/infrastructure': 'search:read',
  'GET /stats/search/behavior': 'search:read',
  'GET /stats/search/trending': 'search:read',
  'GET /stats/search/popular': 'search:read',
  'GET /stats/search/engaged': 'search:read',

  // Posts
  'GET /posts/pending': 'posts:read',
  'GET /posts/pending/:id': 'posts:read',
  'PATCH /posts/:id/approve': 'posts:approve',
  'PATCH /posts/:id/reject': 'posts:approve',
  'POST /posts/:id/retry': 'posts:approve',
  'POST /posts/bulk/approve': 'posts:approve',
  'POST /posts/bulk/reject': 'posts:approve',
  'GET /posts': 'posts:read',
  'GET /posts/stats': 'posts:read',
  'PATCH /posts/:id': 'posts:edit',
  'DELETE /posts/:id': 'posts:delete',
  'POST /posts/:id/restore': 'posts:delete',
  'DELETE /posts/:id/permanent': 'posts:delete',
  'POST /posts/:id/feature': 'posts:manage',
  'POST /posts/:id/unfeature': 'posts:manage',
  'POST /posts/:id/lock': 'posts:manage',
  'POST /posts/:id/unlock': 'posts:manage',
  'POST /posts/:id/bump': 'posts:manage',
  'POST /posts/bulk/status': 'posts:manage',
  'POST /posts/bulk/delete': 'posts:delete',
  'POST /posts/bulk/change-category': 'posts:edit',
  'POST /posts/:id/duplicate': 'posts:edit',
  'PATCH /posts/:id/items/:itemId': 'posts:edit',
  'POST /posts/:id/items': 'posts:edit',
  'DELETE /posts/:id/items/:itemId': 'posts:edit',
  'GET /posts/:id/activity': 'posts:read',
  'GET /posts/:id/revisions': 'posts:read',
  'GET /posts/compare': 'posts:read',
  'GET /posts/:id/comments': 'posts:read',
  'POST /posts/quality-check': 'posts:read',
  'GET /posts/export': 'posts:read',

  // Comments
  'GET /comments': 'comments:read',
  'PATCH /comments/:id': 'comments:moderate',
  'DELETE /comments/:id': 'comments:delete',
  'POST /comments/:id/restore': 'comments:delete',
  'DELETE /comments/:id/permanent': 'comments:delete',
  'POST /comments/:id/hide': 'comments:moderate',
  'POST /comments/:id/unhide': 'comments:moderate',
  'POST /comments/:id/highlight': 'comments:moderate',
  'POST /comments/:id/unhighlight': 'comments:moderate',
  'POST /comments/bulk/delete': 'comments:delete',
  'POST /comments/bulk/hide': 'comments:moderate',
  'POST /comments/:id/flag': 'comments:penalty',
  'POST /comments/bulk/flag': 'comments:penalty',
  'POST /comments/bulk/unflag': 'comments:penalty',
  'POST /comments/:id/dismiss-flag': 'comments:penalty',
  'POST /comments/:id/apply-penalty': 'comments:penalty',
  'GET /comments/stats': 'comments:read',
  'GET /comments/export': 'comments:read',
  'GET /comments/:id/activity': 'comments:read',

  // Users
  'GET /users': 'users:read',
  'GET /users/:user_id': 'users:read',
  'PATCH /users/:user_id/restrict': 'users:restrict',
  'PATCH /users/:user_id/rate-limits': 'users:trust',
  'PATCH /users/:user_id/trust': 'users:trust',
  'GET /users/:user_id/trust-history': 'users:read',

  // Categories
  'GET /categories/stats': 'categories:read',
  'GET /categories/health': 'categories:read',
  'GET /categories/analytics': 'categories:read',
  'GET /categories/export': 'categories:read',
  'GET /categories/orphans': 'categories:read',
  'GET /categories/check-duplicate': 'categories:read',
  'GET /categories/:id/audit': 'categories:read',
  'POST /categories': 'categories:edit',
  'PATCH /categories/:id': 'categories:edit',
  'DELETE /categories/:id': 'categories:edit',
  'POST /categories/:id/duplicate': 'categories:edit',
  'POST /categories/:id/publish': 'categories:edit',
  'POST /categories/:id/hide': 'categories:edit',
  'POST /categories/bulk/feature': 'categories:bulk',
  'POST /categories/bulk/archive': 'categories:bulk',
  'POST /categories/bulk/merge': 'categories:bulk',
  'POST /categories/bulk/reparent': 'categories:bulk',
  'POST /categories/import': 'categories:bulk',

  // Hall of Fame
  'GET /hall-of-fame': 'hof:read',
  'POST /hall-of-fame': 'hof:manage',
  'DELETE /hall-of-fame/:id': 'hof:manage',
  'PATCH /hall-of-fame/reorder': 'hof:manage',
  'PATCH /hall-of-fame/:id': 'hof:manage',
  'GET /hall-of-fame/candidates': 'hof:read',

  // Alerts
  'GET /alerts/thresholds': 'alerts:read',
  'POST /alerts/thresholds': 'alerts:manage',
  'PATCH /alerts/thresholds/:id': 'alerts:manage',
  'DELETE /alerts/thresholds/:id': 'alerts:manage',
  'PATCH /alerts/thresholds/:id/toggle': 'alerts:manage',
  'GET /alerts/notifications': 'alerts:read',
  'GET /alerts/notifications/count': 'alerts:read',
  'GET /alerts/notifications/:id': 'alerts:read',
  'PATCH /alerts/notifications/:id/read': 'alerts:read',
  'PATCH /alerts/notifications/read-all': 'alerts:read',
  'DELETE /alerts/notifications/:id': 'alerts:manage',
  'PATCH /alerts/notifications/:id/settle': 'alerts:manage',
  'PATCH /alerts/notifications/settle-all': 'alerts:manage',
  'GET /alerts/history': 'alerts:read',

  // Audit
  'GET /audit-logs': 'audit:read',
  'GET /audit-logs/stats': 'audit:read',
  'GET /audit-logs/export': 'audit:export',

  // Search
  'GET /search/status': 'search:read',
  'POST /search/reindex': 'search:manage',
  'DELETE /search/index': 'search:manage',
  'GET /search/mappings': 'search:read',
  'GET /search/preview': 'search:read',

  // Notifications
  'GET /messages': 'notifications:read',
  'POST /messages': 'notifications:send',
  'DELETE /messages/:id': 'notifications:send',
  'GET /messages/:id/stats': 'notifications:read',
  'POST /messages/templates': 'notifications:send',
  'GET /messages/templates': 'notifications:read',
  'DELETE /messages/templates/:id': 'notifications:send',

  // Config
  'GET /config': 'config:read',
  'PUT /config': 'config:write',
  'GET /config/impact': 'config:read',
  'GET /config/versions': 'config:read',

  // Mods (super admin only — but mapped for audit trail)
  'POST /mods': 'mods:manage',
  'GET /mods': 'mods:manage',
  'GET /mods/:id': 'mods:manage',
  'PATCH /mods/:id': 'mods:manage',
  'DELETE /mods/:id': 'mods:manage',
  'POST /mods/:id/reset-password': 'mods:manage',
  'GET /mods/permissions': 'mods:manage',
  'GET /mods/presets': 'mods:manage',
};

// Any route not in the map defaults to requiring super_admin
export const DEFAULT_PERMISSION = '__super_admin_only__';
